apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: djj0vsugq-nodejs 
  janus-idp.io/tekton: djj0vsugq-nodejs
  backstage.io/kubernetes-id: djj0vsugq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: djj0vsugq-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml